version: '2'
services:
    postgres:
        container_name: pg-docker
        image: postgres
        ports:
            - '5432:5432'
        restart: always
        logging:
            driver: 'json-file'
            options:
                max-size: '1m'
                max-file: '1'
        environment:
            - POSTGRES_PASSWORD=docker
        volumes:
            - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    microservice-node:
        container_name: microservice-node-express
        image: nic-microservice:latest
        ports:
            - '3000:3000'
        restart: always
        logging:
            driver: 'json-file'
            options:
                max-size: '1m'
                max-file: '1'
        environment:
            - TYPEORM_HOST=postgres
        links:
            - postgres