version: '2'
services:
    postgres:
        container_name: pg-docker
        image: postgres
        ports:
            - '5432:5432'
        restart: always
        logging:
            driver: 'json-file'
            options:
                max-size: '1m'
                max-file: '1'
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=postgres-ms
        volumes:
            - $HOME/docker/volumes/postgres-ms:/var/lib/postgresql/data
    microservice-node:
        container_name: microservice-node-express
        image: 04110000/spn-microservice:latest
        ports:
            - '3000:3000'
        restart: always
        logging:
            driver: 'json-file'
            options:
                max-size: '1m'
                max-file: '1'
        environment:
            - TYPEORM_HOST=postgres
            - TYPEORM_DATABASE=postgres-ms
            - TYPEORM_PORT=5432
            - TYPEORM_CONNECTION=postgres
            - TYPEORM_PASSWORD=docker
            - TYPEORM_USERNAME=postgres
        links:
            - postgres